<a href="https://colab.research.google.com/github/captain7oxic/Pytorch_practice/blob/main/Pytorch_practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
def activation(x):
  return 1/(1+torch.exp(-x))

In [3]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [13]:
torch.mm(features,weights)

RuntimeError: ignored

In [5]:
torch.mm(features,weights.view(5,1))

tensor([[-1.9796]])

In [6]:
#let us generate some more data

In [20]:
torch.manual_seed(7)
#feature vector
features = torch.randn(1,3)
#defining the sizes of tensors

input_vector = features.shape[1]
n_hidden =2
n_output =1

# weights

W1 = torch.randn(input_vector,n_hidden)
W2 = torch.randn(n_hidden,n_output)

#bias

B1 = torch.randn(1,n_hidden)
B2 = torch.randn(1,n_output)



In [21]:
input_vector

3

In [22]:
#calculating the output

h = activation(torch.mm(features,W1)+B1)

In [23]:
output = activation(torch.mm(h,W2)+B2)

In [24]:
output

tensor([[0.3171]])

In [25]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [26]:
output = activation(torch.mm(features,weights.view(5,1))+bias)

In [27]:
output

tensor([[0.1595]])

In [ ]:
#now we will try to do the OCR with help of MNIST dataset of handwritten images of 28*28 pixels

